#!/usr/bin/env bash
# Rebuild lib/extract.bundle.cjs from lib/extract.src.mjs — DIVE-4515.
#
# EXACT pins, never a range: the bundle IS the supply chain for every box that
# installs this plugin, and "whatever npm resolved the day someone rebuilt" is
# not a thing a reviewer can grade. The versions live in lib/pins.json, are
# installed here verbatim, and are printed into every page.meta.json.
#
# Run it, commit the diff, and say in the PR what moved. There is no install
# step on a box: `plugin add` copies files.
set -euo pipefail
cd "$(dirname "$0")"
command -v node >/dev/null || { echo "build.sh needs node" >&2; exit 69; }

DEFUDDLE=$(node -p 'require("./pins.json").defuddle')
LINKEDOM=$(node -p 'require("./pins.json").linkedom')
TURNDOWN=$(node -p 'require("./pins.json").turndown')
ESBUILD=$(node -p 'require("./pins.json").esbuild')

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
cp extract.src.mjs pins.json "$TMP/"
cd "$TMP"
npm init -y >/dev/null
npm install --no-audit --no-fund --save-exact \
    "defuddle@$DEFUDDLE" "linkedom@$LINKEDOM" "turndown@$TURNDOWN" "esbuild@$ESBUILD" >/dev/null

# --format=cjs and no minify: the committed bundle is a file a human is expected
# to be able to grep. Size is not the constraint here, reviewability is.
./node_modules/.bin/esbuild extract.src.mjs \
    --bundle --platform=node --target=node20 --format=cjs \
    --define:__PINS__="$(node -p 'JSON.stringify(require("./pins.json"))')" \
    --outfile=extract.bundle.cjs >/dev/null

cd - >/dev/null
{
  printf '// GENERATED by lib/build.sh — DO NOT EDIT. Source: lib/extract.src.mjs\n'
  printf '// Pinned: defuddle@%s linkedom@%s turndown@%s (esbuild@%s)\n' \
      "$DEFUDDLE" "$LINKEDOM" "$TURNDOWN" "$ESBUILD"
  # A few upstream sources contain whitespace-only blank lines. Normalize only
  # line endings in the generated review artifact so `git diff --check` remains
  # a meaningful release gate and a rebuild is byte-stable.
  sed 's/[[:space:]]*$//' "$TMP/extract.bundle.cjs"
} > extract.bundle.cjs
printf 'built extract.bundle.cjs (%s bytes) — defuddle@%s linkedom@%s\n' \
    "$(stat -c %s extract.bundle.cjs)" "$DEFUDDLE" "$LINKEDOM"
